=== gift-surg/GiftCloudServerBuilder/plugin-resources/project-skeletons/xnat/src/schemas/xdat/display.xsd
<?xml version="1.0" encoding="UTF-8"?>
<!-- edited with XMLSPY v2004 rel. 3 U (http://www.xmlspy.com) by Tim Olsen (Washington University) -->
<xs:schema targetNamespace="http://nrg.wustl.edu/display" xmlns:xs="http://www.w3.org/2001/XMLSchema" xmlns:display="http://nrg.wustl.edu/display" elementFormDefault="qualified" attributeFormDefault="unqualified">
	<xs:element name="Displays">
		<xs:annotation>
			<xs:documentation>Comment describing your root element</xs:documentation>
		</xs:annotation>
		<xs:complexType>
			<xs:sequence>
				<xs:element ref="display:Arc-Definition" minOccurs="0" maxOccurs="unbounded"/>
				<xs:element ref="display:Arc" minOccurs="0" maxOccurs="unbounded"/>
				<xs:element name="DisplayField" maxOccurs="unbounded">
					<xs:complexType>
						<xs:complexContent>
							<xs:extension base="display:FieldType">
								<xs:attribute name="html-content" use="optional">
									<xs:simpleType>
										<xs:restriction base="xs:string">
											<xs:enumeration value="true"/>
											<xs:enumeration value="false"/>
										</xs:restriction>
									</xs:simpleType>
								</xs:attribute>
								<xs:attribute name="visible" type="xs:boolean"/>
							</xs:extension>
						</xs:complexContent>
					</xs:complexType>
				</xs:element>
				<xs:element name="DisplayVersion" maxOccurs="unbounded">
					<xs:complexType>
						<xs:sequence>
							<xs:element name="HTML-Header" type="display:HTML-Cell" minOccurs="0"/>
							<xs:element name="DisplayFieldRef" maxOccurs="unbounded">
								<xs:complexType>
									<xs:attribute name="id" type="xs:string" use="required"/>
									<xs:attribute name="header" type="xs:string" use="optional"/>
									<xs:attribute name="element_name" type="xs:string" use="optional"/>
									<xs:attribute name="type" use="optional">
										<xs:simpleType>
											<xs:restriction base="xs:string">
												<xs:enumeration value="COUNT"/>
											</xs:restriction>
										</xs:simpleType>
									</xs:attribute>
									<xs:attribute name="value" type="xs:string" use="optional"/>
									<xs:attribute name="visible" type="xs:boolean" use="optional"/>
								</xs:complexType>
							</xs:element>
						</xs:sequence>
						<xs:attribute name="versionName" type="xs:string" use="required"/>
						<xs:attribute name="default-order-by" type="xs:string" use="required"/>
						<xs:attribute name="brief-description" type="xs:string"/>
						<xs:attribute name="dark-color" type="xs:string"/>
						<xs:attribute name="light-color" type="xs:string"/>
						<xs:attribute name="default-sort-order" type="xs:string"/>
						<xs:attribute name="allow-diff-columns" type="xs:boolean"/>
					</xs:complexType>
				</xs:element>
				<xs:element name="SchemaLink" minOccurs="0" maxOccurs="unbounded">
					<xs:complexType>
						<xs:sequence>
							<xs:element ref="display:Mapping" minOccurs="0"/>
						</xs:sequence>
						<xs:attribute name="element" type="xs:string" use="required"/>
						<xs:attribute name="type">
							<xs:simpleType>
								<xs:restriction base="xs:string">
									<xs:enumeration value="mapping"/>
								</xs:restriction>
							</xs:simpleType>
						</xs:attribute>
						<xs:attribute name="alias" type="xs:string" use="required"/>
					</xs:complexType>
				</xs:element>
				<xs:element name="ViewLink" minOccurs="0" maxOccurs="unbounded">
					<xs:complexType>
						<xs:sequence>
							<xs:element ref="display:Mapping"/>
						</xs:sequence>
						<xs:attribute name="alias" type="xs:string" use="required"/>
					</xs:complexType>
				</xs:element>
				<xs:element name="SQLView" minOccurs="0" maxOccurs="unbounded">
					<xs:complexType>
						<xs:attribute name="name" type="xs:string" use="required"/>
						<xs:attribute name="sql" type="xs:string" use="required"/>
					</xs:complexType>
				</xs:element>
				<xs:element name="SQLFunction" minOccurs="0" maxOccurs="unbounded">
					<xs:complexType>
						<xs:attribute name="name" type="xs:string"/>
						<xs:attribute name="content" type="xs:string"/>
					</xs:complexType>
				</xs:element>
			</xs:sequence>
			<xs:attribute name="schema-element" type="xs:string"/>
			<xs:attribute name="HTML-header-link" type="xs:string"/>
			<xs:attribute name="value_field" type="xs:string" use="optional"/>
			<xs:attribute name="display_field" type="xs:string" use="optional"/>
			<xs:attribute name="display_label" type="xs:string" use="optional"/>
			<xs:attribute name="brief-description" type="xs:string"/>
			<xs:attribute name="full-description" type="xs:string"/>
		</xs:complexType>
	</xs:element>
	<xs:element name="Mapping">
		<xs:complexType>
			<xs:sequence>
				<xs:element name="MappingColumn" maxOccurs="unbounded">
					<xs:complexType>
						<xs:attribute name="rootElement" type="xs:string"/>
						<xs:attribute name="fieldElement"/>
						<xs:attribute name="mapsTo" type="xs:string"/>
					</xs:complexType>
				</xs:element>
			</xs:sequence>
			<xs:attribute name="TableName" type="xs:string"/>
		</xs:complexType>
	</xs:element>
	<xs:element name="DisplayFieldElement">
		<xs:complexType>
			<xs:attribute name="name" type="xs:string" use="required"/>
			<xs:attribute name="schema-element" type="xs:string" use="optional"/>
			<xs:attribute name="viewName" type="xs:string"/>
			<xs:attribute name="viewColumn" type="xs:string"/>
			<xs:attribute name="xdat-type">
				<xs:simpleType>
					<xs:restriction base="xs:string">
						<xs:enumeration value="COUNT"/>
						<xs:enumeration value="WHERE"/>
					</xs:restriction>
				</xs:simpleType>
			</xs:attribute>
		</xs:complexType>
	</xs:element>
	<xs:complexType name="HTML-Cell">
		<xs:attribute name="width" type="xs:integer"/>
		<xs:attribute name="height" type="xs:integer"/>
		<xs:attribute name="valign">
			<xs:simpleType>
				<xs:restriction base="xs:string">
					<xs:enumeration value="bottom"/>
					<xs:enumeration value="top"/>
				</xs:restriction>
			</xs:simpleType>
		</xs:attribute>
		<xs:attribute name="align">
			<xs:simpleType>
				<xs:restriction base="xs:string">
					<xs:enumeration value="left"/>
					<xs:enumeration value="right"/>
					<xs:enumeration value="center"/>
				</xs:restriction>
			</xs:simpleType>
		</xs:attribute>
		<xs:attribute name="serverLink" type="xs:string"/>
	</xs:complexType>
	<xs:element name="Arc-Definition">
		<xs:complexType>
			<xs:sequence>
				<xs:element name="CommonField" maxOccurs="unbounded">
					<xs:complexType>
						<xs:attribute name="id" type="xs:string" use="required"/>
						<xs:attribute name="type" use="required">
							<xs:simpleType>
								<xs:restriction base="xs:string">
									<xs:enumeration value="DATE"/>
									<xs:enumeration value="INTEGER"/>
									<xs:enumeration value="STRING"/>
								</xs:restriction>
							</xs:simpleType>
						</xs:attribute>
					</xs:complexType>
				</xs:element>
				<xs:element name="Bridge-Element">
					<xs:complexType>
						<xs:attribute name="name" type="xs:string" use="required"/>
						<xs:attribute name="field" type="xs:string" use="required"/>
					</xs:complexType>
				</xs:element>
				<xs:element name="Filter" maxOccurs="unbounded">
					<xs:complexType>
						<xs:attribute name="field" type="xs:string" use="required"/>
						<xs:attribute name="filterType" use="required">
							<xs:simpleType>
								<xs:restriction base="xs:string">
									<xs:enumeration value="closest"/>
									<xs:enumeration value="before"/>
									<xs:enumeration value="equals"/>
									<xs:enumeration value="distinct"/>
								</xs:restriction>
							</xs:simpleType>
						</xs:attribute>
					</xs:complexType>
				</xs:element>
			</xs:sequence>
			<xs:attribute name="Id" type="xs:string" use="required"/>
		</xs:complexType>
	</xs:element>
	<xs:element name="Arc">
		<xs:complexType>
			<xs:sequence>
				<xs:element name="CommonField" maxOccurs="unbounded">
					<xs:complexType>
						<xs:attribute name="id" type="xs:string" use="required"/>
						<xs:attribute name="local-field" type="xs:string" use="required"/>
					</xs:complexType>
				</xs:element>
			</xs:sequence>
			<xs:attribute name="name" type="xs:string" use="required"/>
		</xs:complexType>
	</xs:element>
	<xs:complexType name="FieldType">
		<xs:sequence>
			<xs:element ref="display:DisplayFieldElement" minOccurs="0" maxOccurs="unbounded"/>
			<xs:element name="Content" minOccurs="0">
				<xs:complexType>
					<xs:simpleContent>
						<xs:extension base="xs:string">
							<xs:attribute name="type">
								<xs:simpleType>
									<xs:restriction base="xs:string">
										<xs:enumeration value="sql"/>
										<xs:enumeration value="java"/>
									</xs:restriction>
								</xs:simpleType>
							</xs:attribute>
						</xs:extension>
					</xs:simpleContent>
				</xs:complexType>
			</xs:element>
			<xs:element name="HTML-Link" minOccurs="0">
				<xs:complexType>
					<xs:sequence>
						<xs:element name="SecureLink" minOccurs="0">
							<xs:complexType>
								<xs:sequence>
									<xs:element name="securityMappingValue" maxOccurs="unbounded">
										<xs:complexType>
											<xs:attribute name="displayFieldId" type="xs:string" use="required"/>
											<xs:attribute name="schemaElementMap" type="xs:string" use="required"/>
										</xs:complexType>
									</xs:element>
								</xs:sequence>
								<xs:attribute name="elementName" type="xs:string" use="required"/>
							</xs:complexType>
						</xs:element>
						<xs:element name="Property" maxOccurs="unbounded">
							<xs:complexType>
								<xs:sequence>
									<xs:element name="InsertValue" minOccurs="0" maxOccurs="unbounded">
										<xs:complexType>
											<xs:attribute name="id"/>
											<xs:attribute name="field"/>
										</xs:complexType>
									</xs:element>
								</xs:sequence>
								<xs:attribute name="name">
									<xs:simpleType>
										<xs:restriction base="xs:string"/>
									</xs:simpleType>
								</xs:attribute>
								<xs:attribute name="value"/>
							</xs:complexType>
						</xs:element>
					</xs:sequence>
				</xs:complexType>
			</xs:element>
			<xs:element name="HTML-Cell" type="display:HTML-Cell" minOccurs="0"/>
			<xs:element name="HTML-Image" minOccurs="0">
				<xs:complexType>
					<xs:attribute name="width" type="xs:integer"/>
					<xs:attribute name="height" type="xs:integer"/>
				</xs:complexType>
			</xs:element>
			<xs:element name="description" type="xs:string" minOccurs="0"/>
		</xs:sequence>
		<xs:attribute name="header" type="xs:string" use="required"/>
		<xs:attribute name="id" type="xs:string" use="required"/>
		<xs:attribute name="image" type="xs:boolean" default="false"/>
		<xs:attribute name="sort-by"/>
		<xs:attribute name="sort-order">
			<xs:simpleType>
				<xs:restriction base="xs:string">
					<xs:enumeration value="ASC"/>
					<xs:enumeration value="DESC"/>
				</xs:restriction>
			</xs:simpleType>
		</xs:attribute>
		<xs:attribute name="searchable" type="xs:boolean"/>
		<xs:attribute name="data-type">
			<xs:simpleType>
				<xs:restriction base="xs:string">
					<xs:enumeration value="integer"/>
					<xs:enumeration value="string"/>
					<xs:enumeration value="float"/>
					<xs:enumeration value="date"/>
				</xs:restriction>
			</xs:simpleType>
		</xs:attribute>
	</xs:complexType>
	<xs:complexType name="SubQueryField">
		<xs:complexContent>
			<xs:extension base="display:FieldType">
				<xs:sequence minOccurs="0">
					<xs:element name="SubQuery" type="xs:string" minOccurs="0"/>
					<xs:element name="MappingColumns" minOccurs="0">
						<xs:complexType>
							<xs:sequence minOccurs="0">
								<xs:element name="MappingColumn" minOccurs="0" maxOccurs="unbounded">
									<xs:complexType>
										<xs:attribute name="schemaField" type="xs:string"/>
										<xs:attribute name="queryField" type="xs:string"/>
									</xs:complexType>
								</xs:element>
							</xs:sequence>
						</xs:complexType>
					</xs:element>
				</xs:sequence>
			</xs:extension>
		</xs:complexContent>
	</xs:complexType>
</xs:schema>

=== gift-surg/GiftCloudServerBuilder/plugin-resources/project-skeletons/xnat/src/schemas/xnat/display/xnat_investigatorData_display.xml
<?xml version="1.0" encoding="UTF-8"?><!--Sample XML file generated by XMLSPY v2004 rel. 3 U (http://www.xmlspy.com)--><Displays schema-element="xnat:investigatorData" value_field="INVESTIGATOR_ID" display_field="INVESTIGATOR_NAME" display_label="Investigator" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="../../xdat/display.xsd">	<DisplayField id="INVESTIGATOR_ID" header="Investigator Id" visible="true">		<DisplayFieldElement name="Field1" schema-element="xnat:investigatorData.xnat_investigatorData_id"/>	</DisplayField>	<DisplayField id="RPT" header="" visible="true" image="true">		<Content type="sql">'/@WEBAPP/images/r.gif'::text</Content>		<HTML-Link>			<Property name="HREF" value="none"/>			<Property name="ONCLICK" value="return rpt('@Field1','xnat:investigatorData','xnat:investigatorData.xnat_investigatorData_id');">				<InsertValue id="Field1" field="INVESTIGATOR_ID"/>			</Property>		</HTML-Link>	</DisplayField>	<DisplayField id="INVESTIGATOR_NAME" header="Name" visible="true">		<DisplayFieldElement name="Field2" schema-element="xnat:investigatorData.firstname"/>		<DisplayFieldElement name="Field3" schema-element="xnat:investigatorData.lastname"/>		<Content type="sql">@Field2 || ' ' || @Field3</Content>	</DisplayField>	<DisplayField id="EMAIL" header="Email" visible="true">		<DisplayFieldElement name="Field1" schema-element="xnat:investigatorData.email"/>	</DisplayField>	<DisplayField id="PHONE" header="Phone" visible="true">		<DisplayFieldElement name="Field1" schema-element="xnat:investigatorData.phone"/>	</DisplayField>	<DisplayVersion versionName="listing" default-order-by="INVESTIGATOR_ID" brief-description="Investigator" dark-color="99FF99" light-color="CCFFCC">		<DisplayFieldRef id="RPT"/>		<DisplayFieldRef id="INVESTIGATOR_ID"/>		<DisplayFieldRef id="INVESTIGATOR_NAME"/>		<DisplayFieldRef id="EMAIL"/>		<DisplayFieldRef id="PHONE"/>	</DisplayVersion></Displays>

=== gift-surg/GiftCloudServerBuilder/plugin-resources/project-skeletons/xnat/src/schemas/security/display/role_type_display.xml
<?xml version="1.0" encoding="UTF-8"?><!-- edited with XMLSPY v2004 rel. 3 U (http://www.xmlspy.com) by Tim Olsen (Washington University) --><!--Sample XML file generated by XMLSPY v2004 rel. 3 U (http://www.xmlspy.com)--><Displays xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="../../xdat/display.xsd" schema-element="xdat:role_type">	<DisplayField id="ROLE_NAME" header="Role" visible="true">		<DisplayFieldElement name="Field1" schema-element="xdat:role_type.role_name"/>		<HTML-Link>			<Property name="HREF" value="@WEBAPPapp/action/DisplayItemAction/search_value/@Field1/search_element/xdat:role_type/search_field/xdat:role_type.role_name">				<InsertValue id="Field1" field="ROLE_NAME"/>			</Property>			<Property name="ONCLICK" value="return rpt('@Field1','xdat:role_type','xdat:role_type.role_name');">				<InsertValue id="Field1" field="ROLE_NAME"/>			</Property>		</HTML-Link>	</DisplayField>	<DisplayField id="RPT" header="" visible="true" image="true">		<Content type="sql">'/@WEBAPP/images/r.gif'::text</Content>		<HTML-Link>			<Property name="HREF" value="@WEBAPPapp/action/DisplayItemAction/search_value/@Field1/search_element/xdat:role_type/search_field/xdat:role_type.role_name">				<InsertValue id="Field1" field="ROLE_NAME"/>			</Property>			<Property name="ONCLICK" value="return rpt('@Field1','xdat:role_type','xdat:role_type.role_name');">				<InsertValue id="Field1" field="ROLE_NAME"/>			</Property>		</HTML-Link>	</DisplayField>	<DisplayField id="ACTIVE" header="" visible="true" image="true">		<DisplayFieldElement name="Field1" schema-element="xdat:role_type.meta.status"/>		<Content type="sql">CASE @Field1 WHEN 'active' THEN '/@WEBAPP/images/cg.gif' ELSE  '/@WEBAPP/images/cr.gif' END</Content>	</DisplayField>	<DisplayField id="DESCRIPTION" header="Description" visible="true">		<DisplayFieldElement name="Field1" schema-element="xdat:role_type.description"/>	</DisplayField>	<DisplayField id="ACTION_COUNT" header="Actions" visible="true">		<DisplayFieldElement name="Field1" viewName="ROLE_COUNT" viewColumn="ACTION_COUNT"/>	</DisplayField>	<DisplayField id="SEQ" header="Sequence" visible="true">		<DisplayFieldElement name="Field1" schema-element="xdat:role_type.sequence"/>	</DisplayField>	<DisplayVersion versionName="listing" default-order-by="ROLE_NAME" brief-description="Users" dark-color="DEDEDE" light-color="FFFFFF">		<DisplayFieldRef id="ROLE_NAME"/>		<DisplayFieldRef id="DESCRIPTION"/>		<DisplayFieldRef id="SEQ"/>		<DisplayFieldRef id="ACTION_COUNT"/>	</DisplayVersion>	<ViewLink alias="ROLE_COUNT">		<Mapping TableName="ROLE_COUNT">			<MappingColumn rootElement="xdat:role_type" fieldElement="xdat:role_type.role_name" mapsTo="role1"/>		</Mapping>	</ViewLink>	<SQLView name="ROLE_COUNT" sql="SELECT role_name AS role1,COUNT (map.xdat_a_xdat_action_type_allowe_xdat_role_type_id) AS ACTION_COUNT FROM xdat_role_type role LEFT JOIN xdat_a_xdat_action_type_allowe_xdat_role_type map ON role.role_name=map.xdat_role_type_role_name GROUP BY role_name"/></Displays>

=== gift-surg/GiftCloudServerBuilder/plugin-resources/project-skeletons/xnat/src/schemas/security/display/xdat_infoEntry_display.xml
<?xml version="1.0" encoding="UTF-8"?>
<Displays xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="../../xdat/display.xsd" schema-element="xdat:infoEntry" full-description="Info" brief-description="Info">
	<DisplayField id="INSERT_DATE" header="Inserted" visible="true" searchable="true" data-type="string">
		<DisplayFieldElement name="Field1" schema-element="xdat:infoEntry.meta.insert_date"/>
	</DisplayField>
	<DisplayField id="INSERT_USER" header="Creator" visible="true" searchable="true" data-type="string">
		<DisplayFieldElement name="Field1" schema-element="xdat:infoEntry.meta.insert_user.login"/>
	</DisplayField>
	<DisplayField id="DATE" header="date" visible="true" searchable="true">
		<DisplayFieldElement name="Field1" schema-element="xdat:infoEntry/date"/>
	</DisplayField>
	<DisplayField id="TITLE" header="title" visible="true" searchable="true">
		<DisplayFieldElement name="Field1" schema-element="xdat:infoEntry/title"/>
	</DisplayField>
	<DisplayField id="DESCRIPTION" header="description" visible="true" searchable="true">
		<DisplayFieldElement name="Field1" schema-element="xdat:infoEntry/description"/>
	</DisplayField>
	<DisplayField id="LINK" header="link" visible="true" searchable="true">
		<DisplayFieldElement name="Field1" schema-element="xdat:infoEntry/link"/>
	</DisplayField>
	<DisplayVersion versionName="listing" default-order-by="DATE" default-sort-order="DESC" brief-description="Info" dark-color="9999CC" light-color="CCCCFF">
		<DisplayFieldRef id="DATE"/>
		<DisplayFieldRef id="TITLE"/>
		<DisplayFieldRef id="DESCRIPTION"/>
		<DisplayFieldRef id="LINK"/>
	</DisplayVersion>
	<DisplayVersion versionName="full" default-order-by="DATE" default-sort-order="DESC" brief-description="Info" dark-color="9999CC" light-color="CCCCFF">
		<DisplayFieldRef id="DATE"/>
		<DisplayFieldRef id="TITLE"/>
		<DisplayFieldRef id="DESCRIPTION"/>
		<DisplayFieldRef id="LINK"/>
	</DisplayVersion>
</Displays>

=== gift-surg/GiftCloudServerBuilder/plugin-resources/project-skeletons/xnat/src/schemas/security/display/user_display.xml
<?xml version="1.0" encoding="UTF-8"?>
<!-- edited with XMLSPY v2004 rel. 3 U (http://www.xmlspy.com) by Tim Olsen (Washington University) -->
<!--Sample XML file generated by XMLSPY v2004 rel. 3 U (http://www.xmlspy.com)-->
<Displays xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="../../xdat/display.xsd" schema-element="xdat:user">
	<DisplayField id="LOGIN" header="Username" visible="true">
		<DisplayFieldElement name="Field1" schema-element="xdat:user.login"/>
		<HTML-Link>
			<Property name="HREF" value="@WEBAPPapp/action/DisplayItemAction/search_value/@Field1/search_element/xdat:user/search_field/xdat:user.login">
				<InsertValue id="Field1" field="LOGIN"/>
			</Property>
			<Property name="ONCLICK" value="return rpt('@Field1','xdat:user','xdat:user.login');">
				<InsertValue id="Field1" field="LOGIN"/>
			</Property>
		</HTML-Link>
	</DisplayField>
	<DisplayField id="SU" header="" visible="true" image="true">
		<Content type="sql">'/@WEBAPP/images/su.jpg'::text</Content>
		<HTML-Link>
			<Property name="HREF" value="@WEBAPPapp/action/XDATSudoLogin/sudo_login/@Field1">
				<InsertValue id="Field1" field="LOGIN"/>
			</Property>
		</HTML-Link>
	</DisplayField>
	<DisplayField id="RPT" header="" visible="true" image="true">
		<Content type="sql">'/@WEBAPP/images/r.gif'::text</Content>
		<HTML-Link>
			<Property name="HREF" value="@WEBAPPapp/action/DisplayItemAction/search_value/@Field1/search_element/xdat:user/search_field/xdat:user.login">
				<InsertValue id="Field1" field="LOGIN"/>
			</Property>
			<Property name="ONCLICK" value="return rpt('@Field1','xdat:user','xdat:user.login');">
				<InsertValue id="Field1" field="LOGIN"/>
			</Property>
		</HTML-Link>
	</DisplayField>
	<DisplayField id="ACTIVE" header="Auth." visible="true" image="true">
		<DisplayFieldElement name="Field1" schema-element="xdat:user.meta.status"/>
		<Content type="sql">CASE @Field1 WHEN 'active' THEN '/@WEBAPP/images/cg.gif' ELSE  '/@WEBAPP/images/cr.gif' END</Content>
	</DisplayField>
	<DisplayField id="FIRST" header="First name" visible="true" sort-order="ASC">
		<DisplayFieldElement name="Field1" schema-element="xdat:user.firstname"/>
	</DisplayField>
	<DisplayField id="LAST" header="Last name" visible="true" sort-order="ASC">
		<DisplayFieldElement name="Field1" schema-element="xdat:user.lastname"/>
	</DisplayField>
	<DisplayField id="FIRST_LAST" header="Name" visible="true" sort-order="ASC">
		<DisplayFieldElement name="Field1" schema-element="xdat:user.firstname"/>
		<DisplayFieldElement name="Field2" schema-element="xdat:user.lastname"/>
		<Content type="sql">@Field2 || ', ' || @Field1</Content>
	</DisplayField>
	<DisplayField id="EMAIL" header="Email" visible="true" sort-order="ASC">
		<DisplayFieldElement name="Field1" schema-element="xdat:user.email"/>
		<HTML-Link>
			<Property name="HREF" value="none"/>
			<Property name="ONCLICK" value="return email('@Field1');">
				<InsertValue id="Field1" field="EMAIL"/>
			</Property>
		</HTML-Link>
	</DisplayField>
	<DisplayField id="LAST_LOGIN" header="Last Login" visible="true" sort-order="ASC">
		<DisplayFieldElement name="Field1" viewName="LAST_LOGIN" viewColumn="LOGIN_DATE"/>
		<Content type="sql">CAST (@Field1 AS VARCHAR)</Content>
	</DisplayField>
	<DisplayField id="ENABLED" header="Enabled" visible="true" sort-order="DESC" image="true">
		<DisplayFieldElement name="Field1" schema-element="xdat:user.enabled"/>
		<Content type="sql">CASE @Field1 WHEN 1 THEN '/@WEBAPP/images/cg.gif' WHEN 0 THEN '/@WEBAPP/images/cr.gif' END</Content>
	</DisplayField>
	<DisplayVersion versionName="listing" default-order-by="FIRST_LAST" brief-description="Users" dark-color="DEDEDE" light-color="FFFFFF">
		<DisplayFieldRef id="SU"/>
		<DisplayFieldRef id="LOGIN"/>
		<DisplayFieldRef id="FIRST_LAST"/>
		<DisplayFieldRef id="EMAIL"/>
		<DisplayFieldRef id="LAST_LOGIN"/>
		<DisplayFieldRef id="ACTIVE"/>
		<DisplayFieldRef id="ENABLED"/>
	</DisplayVersion>
	<ViewLink alias="LAST_LOGIN">
		<Mapping TableName="LAST_LOGIN">
			<MappingColumn rootElement="xdat:user" fieldElement="xdat:user.xdat_user_id" mapsTo="USER_ID"/>
		</Mapping>
	</ViewLink>
	<SQLView name="LAST_LOGIN" sql="select DISTINCT ON (user_xdat_user_id) user_xdat_user_id AS USER_ID, login_date FROM xdat_user_login ORDER BY user_xdat_user_id,login_date DESC"/>
	<SQLFunction name="sortedstrings " content="CREATE TYPE sortedstrings AS
   (strings &quot;varchar&quot;,
    sort_order int4);"/>
	<SQLFunction name="getnextview" content="CREATE OR REPLACE FUNCTION getnextview()   RETURNS name AS 
' DECLARE   my_record RECORD;  viewName name; 
BEGIN  FOR my_record IN SELECT c.relname FROM pg_catalog.pg_class AS c LEFT JOIN pg_catalog.pg_namespace AS n ON n.oid = c.relnamespace 
WHERE     c.relkind IN (\'v\') AND n.nspname NOT IN (\'pg_catalog\', \'pg_toast\') AND pg_catalog.pg_table_is_visible(c.oid) LIMIT 1  
LOOP   viewName := my_record.relname;  END LOOP;  RETURN (viewName); END; '  LANGUAGE 'plpgsql' VOLATILE;"/>
	<SQLFunction name="viewcount" content="CREATE OR REPLACE FUNCTION viewcount()   RETURNS int8 AS ' DECLARE   my_record RECORD;  counter int8; 
BEGIN  FOR my_record IN SELECT * FROM (SELECT COUNT (c.relname) AS view_count FROM pg_catalog.pg_class AS c 
LEFT JOIN pg_catalog.pg_namespace AS n ON n.oid = c.relnamespace WHERE     c.relkind IN (\'v\') AND n.nspname 
NOT IN (\'pg_catalog\', \'pg_toast\') AND pg_catalog.pg_table_is_visible(c.oid) LIMIT 1) AS COUNT_TABLE  LOOP   counter := my_record.view_count;  
END LOOP;  RETURN (counter); END; '  LANGUAGE 'plpgsql' VOLATILE;"/>
	<SQLFunction name="getsortedstring" content="CREATE OR REPLACE FUNCTION getsortedstring(&quot;varchar&quot;, int4)   RETURNS sortedstrings AS 'DECLARE  sorted_strings sortedStrings%ROWTYPE; 
BEGIN  sorted_strings.strings:=$1;  sorted_strings.sort_order:=$2;  return sorted_strings; END;'   LANGUAGE 'plpgsql' VOLATILE;"/>
	<SQLFunction name="removeviews" content="CREATE OR REPLACE FUNCTION removeviews()   RETURNS varchar AS ' DECLARE  viewName name;  viewCounter int8; 
BEGIN  SELECT INTO viewName getnextview();  SELECT INTO viewCounter viewCount();  WHILE (viewCounter > 0)   LOOP   
EXECUTE \'DROP VIEW \'|| viewName || \' CASCADE\';   RAISE NOTICE \'DROPPED %. % more.\',viewName,viewCounter;   SELECT INTO viewName getnextview();   
SELECT INTO viewCounter viewCount();  END LOOP;   RETURN (\'DONE\'); END; '   LANGUAGE 'plpgsql' VOLATILE;"/>
	<SQLFunction name="stringstosortedtable" content="CREATE OR REPLACE FUNCTION stringstosortedtable(varchar[])
  RETURNS SETOF sortedstrings AS
'DECLARE  
ss sortedstrings%ROWTYPE; 
i int4;  
BEGIN  
	i :=1 ;
	WHILE ($1[i] IS NOT NULL) 
	LOOP   
		FOR ss IN 
			SELECT * FROM getSortedString($1[i],i) 
		LOOP
			RAISE NOTICE ''SORTED STRING: %,%'',ss.strings,ss.sort_order;
			RETURN NEXT ss;
		END LOOP;
		i:=i+1;  
	END LOOP; 
	RETURN; 
END;'
  LANGUAGE 'plpgsql' VOLATILE;"/>
</Displays>
