=== gift-surg/GiftCloudServerBuilder/plugin-resources/project-skeletons/xnat/src/schemas/xdat/display.xsd
<?xml version="1.0" encoding="UTF-8"?>
<!-- edited with XMLSPY v2004 rel. 3 U (http://www.xmlspy.com) by Tim Olsen (Washington University) -->
<xs:schema targetNamespace="http://nrg.wustl.edu/display" xmlns:xs="http://www.w3.org/2001/XMLSchema" xmlns:display="http://nrg.wustl.edu/display" elementFormDefault="qualified" attributeFormDefault="unqualified">
	<xs:element name="Displays">
		<xs:annotation>
			<xs:documentation>Comment describing your root element</xs:documentation>
		</xs:annotation>
		<xs:complexType>
			<xs:sequence>
				<xs:element ref="display:Arc-Definition" minOccurs="0" maxOccurs="unbounded"/>
				<xs:element ref="display:Arc" minOccurs="0" maxOccurs="unbounded"/>
				<xs:element name="DisplayField" maxOccurs="unbounded">
					<xs:complexType>
						<xs:complexContent>
							<xs:extension base="display:FieldType">
								<xs:attribute name="html-content" use="optional">
									<xs:simpleType>
										<xs:restriction base="xs:string">
											<xs:enumeration value="true"/>
											<xs:enumeration value="false"/>
										</xs:restriction>
									</xs:simpleType>
								</xs:attribute>
								<xs:attribute name="visible" type="xs:boolean"/>
							</xs:extension>
						</xs:complexContent>
					</xs:complexType>
				</xs:element>
				<xs:element name="DisplayVersion" maxOccurs="unbounded">
					<xs:complexType>
						<xs:sequence>
							<xs:element name="HTML-Header" type="display:HTML-Cell" minOccurs="0"/>
							<xs:element name="DisplayFieldRef" maxOccurs="unbounded">
								<xs:complexType>
									<xs:attribute name="id" type="xs:string" use="required"/>
									<xs:attribute name="header" type="xs:string" use="optional"/>
									<xs:attribute name="element_name" type="xs:string" use="optional"/>
									<xs:attribute name="type" use="optional">
										<xs:simpleType>
											<xs:restriction base="xs:string">
												<xs:enumeration value="COUNT"/>
											</xs:restriction>
										</xs:simpleType>
									</xs:attribute>
									<xs:attribute name="value" type="xs:string" use="optional"/>
									<xs:attribute name="visible" type="xs:boolean" use="optional"/>
								</xs:complexType>
							</xs:element>
						</xs:sequence>
						<xs:attribute name="versionName" type="xs:string" use="required"/>
						<xs:attribute name="default-order-by" type="xs:string" use="required"/>
						<xs:attribute name="brief-description" type="xs:string"/>
						<xs:attribute name="dark-color" type="xs:string"/>
						<xs:attribute name="light-color" type="xs:string"/>
						<xs:attribute name="default-sort-order" type="xs:string"/>
						<xs:attribute name="allow-diff-columns" type="xs:boolean"/>
					</xs:complexType>
				</xs:element>
				<xs:element name="SchemaLink" minOccurs="0" maxOccurs="unbounded">
					<xs:complexType>
						<xs:sequence>
							<xs:element ref="display:Mapping" minOccurs="0"/>
						</xs:sequence>
						<xs:attribute name="element" type="xs:string" use="required"/>
						<xs:attribute name="type">
							<xs:simpleType>
								<xs:restriction base="xs:string">
									<xs:enumeration value="mapping"/>
								</xs:restriction>
							</xs:simpleType>
						</xs:attribute>
						<xs:attribute name="alias" type="xs:string" use="required"/>
					</xs:complexType>
				</xs:element>
				<xs:element name="ViewLink" minOccurs="0" maxOccurs="unbounded">
					<xs:complexType>
						<xs:sequence>
							<xs:element ref="display:Mapping"/>
						</xs:sequence>
						<xs:attribute name="alias" type="xs:string" use="required"/>
					</xs:complexType>
				</xs:element>
				<xs:element name="SQLView" minOccurs="0" maxOccurs="unbounded">
					<xs:complexType>
						<xs:attribute name="name" type="xs:string" use="required"/>
						<xs:attribute name="sql" type="xs:string" use="required"/>
					</xs:complexType>
				</xs:element>
				<xs:element name="SQLFunction" minOccurs="0" maxOccurs="unbounded">
					<xs:complexType>
						<xs:attribute name="name" type="xs:string"/>
						<xs:attribute name="content" type="xs:string"/>
					</xs:complexType>
				</xs:element>
			</xs:sequence>
			<xs:attribute name="schema-element" type="xs:string"/>
			<xs:attribute name="HTML-header-link" type="xs:string"/>
			<xs:attribute name="value_field" type="xs:string" use="optional"/>
			<xs:attribute name="display_field" type="xs:string" use="optional"/>
			<xs:attribute name="display_label" type="xs:string" use="optional"/>
			<xs:attribute name="brief-description" type="xs:string"/>
			<xs:attribute name="full-description" type="xs:string"/>
		</xs:complexType>
	</xs:element>
	<xs:element name="Mapping">
		<xs:complexType>
			<xs:sequence>
				<xs:element name="MappingColumn" maxOccurs="unbounded">
					<xs:complexType>
						<xs:attribute name="rootElement" type="xs:string"/>
						<xs:attribute name="fieldElement"/>
						<xs:attribute name="mapsTo" type="xs:string"/>
					</xs:complexType>
				</xs:element>
			</xs:sequence>
			<xs:attribute name="TableName" type="xs:string"/>
		</xs:complexType>
	</xs:element>
	<xs:element name="DisplayFieldElement">
		<xs:complexType>
			<xs:attribute name="name" type="xs:string" use="required"/>
			<xs:attribute name="schema-element" type="xs:string" use="optional"/>
			<xs:attribute name="viewName" type="xs:string"/>
			<xs:attribute name="viewColumn" type="xs:string"/>
			<xs:attribute name="xdat-type">
				<xs:simpleType>
					<xs:restriction base="xs:string">
						<xs:enumeration value="COUNT"/>
						<xs:enumeration value="WHERE"/>
					</xs:restriction>
				</xs:simpleType>
			</xs:attribute>
		</xs:complexType>
	</xs:element>
	<xs:complexType name="HTML-Cell">
		<xs:attribute name="width" type="xs:integer"/>
		<xs:attribute name="height" type="xs:integer"/>
		<xs:attribute name="valign">
			<xs:simpleType>
				<xs:restriction base="xs:string">
					<xs:enumeration value="bottom"/>
					<xs:enumeration value="top"/>
				</xs:restriction>
			</xs:simpleType>
		</xs:attribute>
		<xs:attribute name="align">
			<xs:simpleType>
				<xs:restriction base="xs:string">
					<xs:enumeration value="left"/>
					<xs:enumeration value="right"/>
					<xs:enumeration value="center"/>
				</xs:restriction>
			</xs:simpleType>
		</xs:attribute>
		<xs:attribute name="serverLink" type="xs:string"/>
	</xs:complexType>
	<xs:element name="Arc-Definition">
		<xs:complexType>
			<xs:sequence>
				<xs:element name="CommonField" maxOccurs="unbounded">
					<xs:complexType>
						<xs:attribute name="id" type="xs:string" use="required"/>
						<xs:attribute name="type" use="required">
							<xs:simpleType>
								<xs:restriction base="xs:string">
									<xs:enumeration value="DATE"/>
									<xs:enumeration value="INTEGER"/>
									<xs:enumeration value="STRING"/>
								</xs:restriction>
							</xs:simpleType>
						</xs:attribute>
					</xs:complexType>
				</xs:element>
				<xs:element name="Bridge-Element">
					<xs:complexType>
						<xs:attribute name="name" type="xs:string" use="required"/>
						<xs:attribute name="field" type="xs:string" use="required"/>
					</xs:complexType>
				</xs:element>
				<xs:element name="Filter" maxOccurs="unbounded">
					<xs:complexType>
						<xs:attribute name="field" type="xs:string" use="required"/>
						<xs:attribute name="filterType" use="required">
							<xs:simpleType>
								<xs:restriction base="xs:string">
									<xs:enumeration value="closest"/>
									<xs:enumeration value="before"/>
									<xs:enumeration value="equals"/>
									<xs:enumeration value="distinct"/>
								</xs:restriction>
							</xs:simpleType>
						</xs:attribute>
					</xs:complexType>
				</xs:element>
			</xs:sequence>
			<xs:attribute name="Id" type="xs:string" use="required"/>
		</xs:complexType>
	</xs:element>
	<xs:element name="Arc">
		<xs:complexType>
			<xs:sequence>
				<xs:element name="CommonField" maxOccurs="unbounded">
					<xs:complexType>
						<xs:attribute name="id" type="xs:string" use="required"/>
						<xs:attribute name="local-field" type="xs:string" use="required"/>
					</xs:complexType>
				</xs:element>
			</xs:sequence>
			<xs:attribute name="name" type="xs:string" use="required"/>
		</xs:complexType>
	</xs:element>
	<xs:complexType name="FieldType">
		<xs:sequence>
			<xs:element ref="display:DisplayFieldElement" minOccurs="0" maxOccurs="unbounded"/>
			<xs:element name="Content" minOccurs="0">
				<xs:complexType>
					<xs:simpleContent>
						<xs:extension base="xs:string">
							<xs:attribute name="type">
								<xs:simpleType>
									<xs:restriction base="xs:string">
										<xs:enumeration value="sql"/>
										<xs:enumeration value="java"/>
									</xs:restriction>
								</xs:simpleType>
							</xs:attribute>
						</xs:extension>
					</xs:simpleContent>
				</xs:complexType>
			</xs:element>
			<xs:element name="HTML-Link" minOccurs="0">
				<xs:complexType>
					<xs:sequence>
						<xs:element name="SecureLink" minOccurs="0">
							<xs:complexType>
								<xs:sequence>
									<xs:element name="securityMappingValue" maxOccurs="unbounded">
										<xs:complexType>
											<xs:attribute name="displayFieldId" type="xs:string" use="required"/>
											<xs:attribute name="schemaElementMap" type="xs:string" use="required"/>
										</xs:complexType>
									</xs:element>
								</xs:sequence>
								<xs:attribute name="elementName" type="xs:string" use="required"/>
							</xs:complexType>
						</xs:element>
						<xs:element name="Property" maxOccurs="unbounded">
							<xs:complexType>
								<xs:sequence>
									<xs:element name="InsertValue" minOccurs="0" maxOccurs="unbounded">
										<xs:complexType>
											<xs:attribute name="id"/>
											<xs:attribute name="field"/>
										</xs:complexType>
									</xs:element>
								</xs:sequence>
								<xs:attribute name="name">
									<xs:simpleType>
										<xs:restriction base="xs:string"/>
									</xs:simpleType>
								</xs:attribute>
								<xs:attribute name="value"/>
							</xs:complexType>
						</xs:element>
					</xs:sequence>
				</xs:complexType>
			</xs:element>
			<xs:element name="HTML-Cell" type="display:HTML-Cell" minOccurs="0"/>
			<xs:element name="HTML-Image" minOccurs="0">
				<xs:complexType>
					<xs:attribute name="width" type="xs:integer"/>
					<xs:attribute name="height" type="xs:integer"/>
				</xs:complexType>
			</xs:element>
			<xs:element name="description" type="xs:string" minOccurs="0"/>
		</xs:sequence>
		<xs:attribute name="header" type="xs:string" use="required"/>
		<xs:attribute name="id" type="xs:string" use="required"/>
		<xs:attribute name="image" type="xs:boolean" default="false"/>
		<xs:attribute name="sort-by"/>
		<xs:attribute name="sort-order">
			<xs:simpleType>
				<xs:restriction base="xs:string">
					<xs:enumeration value="ASC"/>
					<xs:enumeration value="DESC"/>
				</xs:restriction>
			</xs:simpleType>
		</xs:attribute>
		<xs:attribute name="searchable" type="xs:boolean"/>
		<xs:attribute name="data-type">
			<xs:simpleType>
				<xs:restriction base="xs:string">
					<xs:enumeration value="integer"/>
					<xs:enumeration value="string"/>
					<xs:enumeration value="float"/>
					<xs:enumeration value="date"/>
				</xs:restriction>
			</xs:simpleType>
		</xs:attribute>
	</xs:complexType>
	<xs:complexType name="SubQueryField">
		<xs:complexContent>
			<xs:extension base="display:FieldType">
				<xs:sequence minOccurs="0">
					<xs:element name="SubQuery" type="xs:string" minOccurs="0"/>
					<xs:element name="MappingColumns" minOccurs="0">
						<xs:complexType>
							<xs:sequence minOccurs="0">
								<xs:element name="MappingColumn" minOccurs="0" maxOccurs="unbounded">
									<xs:complexType>
										<xs:attribute name="schemaField" type="xs:string"/>
										<xs:attribute name="queryField" type="xs:string"/>
									</xs:complexType>
								</xs:element>
							</xs:sequence>
						</xs:complexType>
					</xs:element>
				</xs:sequence>
			</xs:extension>
		</xs:complexContent>
	</xs:complexType>
</xs:schema>

=== gift-surg/GiftCloudServerBuilder/plugin-resources/project-skeletons/xnat/src/schemas/pipeline/display/workflowData_display.xml
<?xml version="1.0" encoding="UTF-8"?>
<Displays xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="../../xdat/display.xsd" schema-element="wrk:workflowData" full-description="Workflow" brief-description="Workflow">
	<DisplayField id="DATA_TYPE" header="data_type" visible="true" searchable="true">
		<DisplayFieldElement name="Field1" schema-element="wrk:workflowData/data_type"/>
	</DisplayField>
	<DisplayField id="ID" header="ID" visible="true" searchable="true">
		<DisplayFieldElement name="Field1" schema-element="wrk:workflowData/ID"/>
		<HTML-Link>
			<Property name="HREF" value="@WEBAPPapp/action/DisplayItemAction/search_value/@Field1/search_element/@Field2/search_field/@Field2.ID">
				<InsertValue id="Field1" field="ID"/>
				<InsertValue id="Field2" field="DATA_TYPE"/>
			</Property>
			<Property name="ONCLICK" value="return rpt('@Field1','@Field2','@Field2.ID');">
				<InsertValue id="Field1" field="ID"/>
				<InsertValue id="Field2" field="DATA_TYPE"/>
			</Property>
		</HTML-Link>
	</DisplayField>
	<DisplayField id="EXTERNALID" header="ExternalID" visible="true" searchable="true">
		<DisplayFieldElement name="Field1" schema-element="wrk:workflowData/ExternalID"/>
	</DisplayField>
	<DisplayField id="CURRENT_STEP_LAUNCH_TIME" header="current_step_launch_time" visible="true" searchable="true">
		<DisplayFieldElement name="Field1" schema-element="wrk:workflowData/current_step_launch_time"/>
	</DisplayField>
	<DisplayField id="CURRENT_STEP_ID" header="current_step_id" visible="true" searchable="true">
		<DisplayFieldElement name="Field1" schema-element="wrk:workflowData/current_step_id"/>
	</DisplayField>
	<DisplayField id="STATUS" header="status" visible="true" searchable="true">
		<DisplayFieldElement name="Field1" schema-element="wrk:workflowData/status"/>
		<Content type="sql">'&lt;B&gt;' || CASE @Field1 WHEN 'Complete' THEN '&lt;FONT COLOR=green&gt;Complete&lt;/FONT&gt;' WHEN 'In Progress' THEN '&lt;FONT COLOR=yellow&gt;In Progress&lt;/FONT&gt;' WHEN 'Running' THEN '&lt;FONT COLOR=yellow&gt;Running&lt;/FONT&gt;' WHEN 'Queued' THEN '&lt;FONT COLOR=orange&gt;Queued&lt;/FONT&gt;' WHEN 'Failed' THEN '&lt;FONT COLOR=red&gt;Failed&lt;/FONT&gt;' ELSE '&lt;FONT COLOR=orange&gt;' || @Field1 || '&lt;/FONT&gt;' END || '&lt;/B&gt;' </Content>
		<HTML-Link>
			<Property name="TITLE" value="@Field1">
				<InsertValue id="Field1" field="CURRENT_STEP_ID"/>
			</Property>
		</HTML-Link>
	</DisplayField>
	<DisplayField id="PIPELINE_NAME" header="pipeline_name" visible="true" searchable="true">
		<DisplayFieldElement name="Field1" schema-element="wrk:workflowData/pipeline_name"/>
	</DisplayField>
	<DisplayField id="NEXT_STEP_ID" header="next_step_id" visible="true" searchable="true">
		<DisplayFieldElement name="Field1" schema-element="wrk:workflowData/next_step_id"/>
	</DisplayField>
	<DisplayField id="STEP_DESCRIPTION" header="step_description" visible="true" searchable="true">
		<DisplayFieldElement name="Field1" schema-element="wrk:workflowData/step_description"/>
	</DisplayField>
	<DisplayField id="LAUNCH_TIME" header="launch_time" visible="true" searchable="true">
		<DisplayFieldElement name="Field1" schema-element="wrk:workflowData/launch_time"/>
	</DisplayField>
	<DisplayField id="PERCENTAGECOMPLETE" header="percentageComplete" visible="true" searchable="true">
		<DisplayFieldElement name="Field1" schema-element="wrk:workflowData/percentageComplete"/>
	</DisplayField>
	<DisplayField id="LAST_MODIFIED" header="Modified" visible="false" searchable="true" data-type="date">
		<DisplayFieldElement name="Field1" schema-element="wrk:workflowData/meta/insert_date"/>
		<DisplayFieldElement name="Field2" schema-element="wrk:workflowData/meta/last_modified"/>
		<Content type="sql">COALESCE(@Field2, @Field1)</Content>
	</DisplayField>
	<DisplayVersion versionName="listing" default-order-by="LAST_MODIFIED" default-sort-order="DESC" brief-description="Workflow" dark-color="9999CC" light-color="CCCCFF">
		<DisplayFieldRef id="ID"/>
		<DisplayFieldRef id="LAUNCH_TIME"/>
		<DisplayFieldRef id="STATUS"/>
		<DisplayFieldRef id="LAST_MODIFIED"/>
	</DisplayVersion>
</Displays>

=== gift-surg/GiftCloudServerBuilder/plugin-resources/project-skeletons/xnat/src/schemas/security/display/xdat_userGroup_display.xml
<?xml version="1.0" encoding="UTF-8"?><!-- edited with XMLSPY v2004 rel. 3 U (http://www.xmlspy.com) by Tim Olsen (Washington University) --><!--Sample XML file generated by XMLSPY v2004 rel. 3 U (http://www.xmlspy.com)--><Displays xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="../../xdat/display.xsd" schema-element="xdat:userGroup">	<DisplayField id="ID" header="ID" visible="true">		<DisplayFieldElement name="Field1" schema-element="xdat:userGroup.id"/>		<HTML-Link>			<Property name="HREF" value="@WEBAPPapp/action/DisplayItemAction/search_value/@Field1/search_element/xdat:user/search_field/xdat:userGroup.ID">				<InsertValue id="Field1" field="ID"/>			</Property>			<Property name="ONCLICK" value="return rpt('@Field1','xdat:userGroup','xdat:userGroup.ID');">				<InsertValue id="Field1" field="ID"/>			</Property>		</HTML-Link>	</DisplayField>	<DisplayField id="DISPLAY_NAME" header="Name" visible="true" sort-order="ASC">		<DisplayFieldElement name="Field1" schema-element="xdat:userGroup.displayName"/>	</DisplayField>	<DisplayVersion versionName="listing" default-order-by="ID" brief-description="Users" dark-color="DEDEDE" light-color="FFFFFF">		<DisplayFieldRef id="ID"/>		<DisplayFieldRef id="DISPLAY_NAME"/>	</DisplayVersion></Displays>

=== gift-surg/GiftCloudServerBuilder/plugin-resources/project-skeletons/xnat/src/schemas/security/display/element_security_display.xml
<?xml version="1.0" encoding="UTF-8"?><!--Sample XML file generated by XMLSPY v2004 rel. 3 U (http://www.xmlspy.com)--><Displays xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="../../xdat/display.xsd" schema-element="xdat:element_security">	<DisplayField id="ELEMENT_NAME" header="Element" visible="true">		<DisplayFieldElement name="Field1" schema-element="xdat:element_security.element_name"/>		<HTML-Link>			<Property name="HREF" value="@WEBAPPapp/action/DisplayItemAction/search_value/@Field1/search_element/xdat:element_security/search_field/xdat:element_security.element_name">				<InsertValue id="Field1" field="ELEMENT_NAME"/>			</Property>			<Property name="ONCLICK" value="return rpt('@Field1','xdat:element_security','xdat:element_security.element_name');">				<InsertValue id="Field1" field="ELEMENT_NAME"/>			</Property>		</HTML-Link>	</DisplayField>	<DisplayField id="SECURE" header="Secured" visible="true" sort-order="DESC" image="true">		<DisplayFieldElement name="Field1" schema-element="xdat:element_security.secure"/>		<Content type="sql">CASE @Field1 WHEN 1 THEN '/@WEBAPP/images/cg.gif' WHEN 0 THEN '/@WEBAPP/images/cr.gif' END</Content>	</DisplayField>	<DisplayField id="BROWSE" header="Browse" visible="true" sort-order="DESC" image="true">		<DisplayFieldElement name="Field1" schema-element="xdat:element_security.browse"/>		<Content type="sql">CASE @Field1 WHEN 1 THEN '/@WEBAPP/images/cg.gif' WHEN 0 THEN '/@WEBAPP/images/cr.gif' END</Content>	</DisplayField>	<DisplayField id="SEQUENCE" header="Order" visible="true" sort-order="ASC">		<DisplayFieldElement name="Field1" schema-element="xdat:element_security.sequence"/>	</DisplayField>	<DisplayVersion versionName="listing" default-order-by="ELEMENT_NAME" brief-description="Users" dark-color="DEDEDE" light-color="FFFFFF">		<DisplayFieldRef id="ELEMENT_NAME"/>		<DisplayFieldRef id="SECURE"/>		<DisplayFieldRef id="BROWSE"/>	</DisplayVersion></Displays>

=== gift-surg/GiftCloudServerBuilder/plugin-resources/project-skeletons/xnat/src/schemas/security/display/xdat_newsEntry_display.xml
<?xml version="1.0" encoding="UTF-8"?>
<Displays xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="../../xdat/display.xsd" schema-element="xdat:newsEntry" full-description="News" brief-description="News">
	<DisplayField id="INSERT_DATE" header="Inserted" visible="true" searchable="true" data-type="string">
		<DisplayFieldElement name="Field1" schema-element="xdat:newsEntry.meta.insert_date"/>
	</DisplayField>
	<DisplayField id="INSERT_USER" header="Creator" visible="true" searchable="true" data-type="string">
		<DisplayFieldElement name="Field1" schema-element="xdat:newsEntry.meta.insert_user.login"/>
	</DisplayField>
	<DisplayField id="DATE" header="date" visible="true" searchable="true">
		<DisplayFieldElement name="Field1" schema-element="xdat:newsEntry/date"/>
	</DisplayField>
	<DisplayField id="TITLE" header="title" visible="true" searchable="true">
		<DisplayFieldElement name="Field1" schema-element="xdat:newsEntry/title"/>
	</DisplayField>
	<DisplayField id="DESCRIPTION" header="description" visible="true" searchable="true">
		<DisplayFieldElement name="Field1" schema-element="xdat:newsEntry/description"/>
	</DisplayField>
	<DisplayField id="LINK" header="link" visible="true" searchable="true">
		<DisplayFieldElement name="Field1" schema-element="xdat:newsEntry/link"/>
	</DisplayField>
	<DisplayVersion versionName="listing" default-order-by="DATE" default-sort-order="DESC" brief-description="News" dark-color="9999CC" light-color="CCCCFF">
		<DisplayFieldRef id="DATE"/>
		<DisplayFieldRef id="TITLE"/>
		<DisplayFieldRef id="DESCRIPTION"/>
		<DisplayFieldRef id="LINK"/>
	</DisplayVersion>
	<DisplayVersion versionName="full" default-order-by="DATE" default-sort-order="DESC" brief-description="News" dark-color="9999CC" light-color="CCCCFF">
		<DisplayFieldRef id="DATE"/>
		<DisplayFieldRef id="TITLE"/>
		<DisplayFieldRef id="DESCRIPTION"/>
		<DisplayFieldRef id="LINK"/>
	</DisplayVersion>
</Displays>

=== gift-surg/GiftCloudServerBuilder/plugin-resources/project-skeletons/xnat/src/schemas/security/display/xdat_stored_search_display.xml
<?xml version="1.0" encoding="UTF-8"?>
<!--
  ~ D:/Development/XNAT/1.6/xnat_builder_1_6dev/plugin-resources/project-skeletons/xnat/src/schemas/security/display/xdat_stored_search_display.xml
  ~ XNAT http://www.xnat.org
  ~ Copyright (c) 2014, Washington University School of Medicine
  ~ All Rights Reserved
  ~
  ~ Released under the Simplified BSD.
  ~
  ~ Last modified 2/7/14 12:19 PM
  -->
<Displays xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="../../xdat/display.xsd" schema-element="xdat:stored_search" full-description="Bundles" brief-description="Bundles">
	<DisplayField id="ROOT_ELEMENT_NAME" header="pivot" visible="true" searchable="true">
		<DisplayFieldElement name="Field1" schema-element="xdat:stored_search/root_element_name"/>
	</DisplayField>
	<DisplayField id="SORT_BY_ELEMENT_NAME" header="sort by" visible="true" searchable="true">
		<DisplayFieldElement name="Field1" schema-element="xdat:stored_search/sort_by/element_name"/>
	</DisplayField>
	<DisplayField id="SORT_BY_FIELD_ID" header="sort by" visible="true" searchable="true">
		<DisplayFieldElement name="Field1" schema-element="xdat:stored_search/sort_by/field_ID"/>
	</DisplayField>
	<DisplayField id="LAYERED_SEQUENCE" header="Sequence" visible="true" searchable="true">
		<DisplayFieldElement name="Field1" schema-element="xdat:stored_search/layeredSequence"/>
	</DisplayField>
	<DisplayField id="ID" header="ID" visible="true" searchable="true">
		<DisplayFieldElement name="Field1" schema-element="xdat:stored_search/ID"/>
		<HTML-Link>
			<Property name="HREF" value="@WEBAPPapp/action/DisplayItemAction/search_value/@Field1/search_element/xdat:stored_search/search_field/xdat:stored_search.ID">
				<InsertValue id="Field1" field="ID"/>
			</Property>
			<Property name="ONCLICK" value="return rpt('@Field1','xdat:stored_search','xdat:stored_search.ID');">
				<InsertValue id="Field1" field="ID"/>
			</Property>
		</HTML-Link>
	</DisplayField>
	<DisplayField id="DESCRIPTION" header="Full Desc" visible="true" searchable="true">
		<DisplayFieldElement name="Field1" schema-element="xdat:stored_search/description"/>
	</DisplayField>
	<DisplayField id="BRIEF_DESCRIPTION" header="Brief Desc" visible="true" searchable="true">
		<DisplayFieldElement name="Field1" schema-element="xdat:stored_search/brief-description"/>
	</DisplayField>
	<DisplayVersion versionName="listing" default-order-by="ROOT_ELEMENT_NAME" default-sort-order="DESC" brief-description="bundle" dark-color="9999CC" light-color="CCCCFF">
		<DisplayFieldRef id="ID"/>
		<DisplayFieldRef id="BRIEF_DESCRIPTION"/>
		<DisplayFieldRef id="DESCRIPTION"/>
		<DisplayFieldRef id="ROOT_ELEMENT_NAME"/>
		<DisplayFieldRef id="SORT_BY_ELEMENT_NAME"/>
		<DisplayFieldRef id="SORT_BY_FIELD_ID"/>
		<DisplayFieldRef id="LAYERED_SEQUENCE"/>
	</DisplayVersion>
</Displays>
