=== gift-surg/GiftCloudServerBuilder/plugin-resources/project-skeletons/xnat/src/schemas/xdat/instance.xsd
<?xml version="1.0" encoding="UTF-8"?>
<!-- edited with XMLSPY v2004 rel. 3 U (http://www.xmlspy.com) by Tim Olsen (Washington University) -->
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema" elementFormDefault="qualified" attributeFormDefault="unqualified">
	<xs:element name="Instance_Settings">
		<xs:complexType>
			<xs:sequence>
				<xs:element name="Databases">
					<xs:complexType>
						<xs:sequence>
							<xs:element name="Database">
								<xs:complexType>
									<xs:attribute name="Type">
										<xs:simpleType>
											<xs:restriction base="xs:string">
												<xs:enumeration value="POSTGRESQL"/>
												<xs:enumeration value="MYSQL"/>
											</xs:restriction>
										</xs:simpleType>
									</xs:attribute>
									<xs:attribute name="Id" type="xs:string"/>
									<xs:attribute name="Url" type="xs:string"/>
									<xs:attribute name="User" type="xs:string"/>
									<xs:attribute name="Pass" type="xs:string"/>
									<xs:attribute name="Driver" type="xs:string"/>
									<xs:attribute name="MaxConnections" type="xs:integer"/>
								</xs:complexType>
							</xs:element>
						</xs:sequence>
					</xs:complexType>
				</xs:element>
				<xs:element name="Package" minOccurs="0">
					<xs:complexType>
						<xs:attribute name="Name" type="xs:string"/>
					</xs:complexType>
				</xs:element>
				<xs:element name="Models">
					<xs:complexType>
						<xs:sequence>
							<xs:element name="Data_Model" maxOccurs="unbounded">
								<xs:complexType>
									<xs:attribute name="File_Name" type="xs:string"/>
									<xs:attribute name="File_Location" type="xs:string"/>
									<xs:attribute name="DB" type="xs:string"/>
									<xs:attribute name="package" type="xs:string" use="optional"/>
								</xs:complexType>
							</xs:element>
						</xs:sequence>
					</xs:complexType>
				</xs:element>
				<xs:element name="Data_Type_Codes" minOccurs="0">
					<xs:complexType>
						<xs:sequence>
							<xs:element name="Type_Code_Mapping" maxOccurs="unbounded">
								<xs:complexType>
									<xs:attribute name="Model_Id" type="xs:string"/>
									<xs:attribute name="Model_Element" type="xs:string"/>
									<xs:attribute name="Code" type="xs:string"/>
									<xs:attribute name="Brief_Description" type="xs:string"/>
									<xs:attribute name="Full_Description" type="xs:string"/>
									<xs:attribute name="Log_Location" type="xs:string"/>
								</xs:complexType>
							</xs:element>
						</xs:sequence>
					</xs:complexType>
				</xs:element>
				<xs:element name="Pivots" minOccurs="0">
					<xs:complexType>
						<xs:sequence>
							<xs:element name="Pivot" maxOccurs="unbounded">
								<xs:complexType>
									<xs:attribute name="Model_Id" type="xs:string"/>
									<xs:attribute name="Model_Element" type="xs:string"/>
									<xs:attribute name="Mapping1" type="xs:string"/>
									<xs:attribute name="Mapping2" type="xs:string"/>
								</xs:complexType>
							</xs:element>
						</xs:sequence>
					</xs:complexType>
				</xs:element>
			</xs:sequence>
			<xs:attribute name="admin_email" type="xs:string"/>
			<xs:attribute name="smtp_server" type="xs:string" use="optional"/>
			<xs:attribute name="archive_root_path" type="xs:string" use="optional"/>
			<xs:attribute name="cache_path" type="xs:string" use="optional"/>
			<xs:attribute name="prearchive_path" type="xs:string" use="optional"/>
			<xs:attribute name="site_url" type="xs:string" use="optional"/>
		</xs:complexType>
	</xs:element>
</xs:schema>

=== gift-surg/GiftCloudServerBuilder/plugin-resources/project-skeletons/xnat/InstanceSettings.xml
<?xml version="1.0" encoding="UTF-8"?>
<!-- edited with XMLSPY v2004 rel. 3 U (http://www.xmlspy.com) by Tim Olsen (Washington University) -->
<Instance_Settings xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="%XDAT_PROJECT%/schemas/xdat/instance.xsd" site_url="%SITE_URL%" admin_email="%ADMIN_EMAIL%" archive_root_path="%ARCHIVE_LOCATION%" prearchive_path="%PREARC_LOCATION%" cache_path="%CACHE_LOCATION%" smtp_server="%SMTP_SERVER%" ftp_path="%FTP_LOCATION%" build_path="%BUILD_LOCATION%" pipeline_path="%PIPELINE_HOME%" require_login="%REQUIRE_LOGIN%" user_registration="%USER_REGISTRATION%" enable_csrf_token="%ENABLE_CSRF_TOKEN%">
	<Databases>
		<Database Type="POSTGRESQL" Id="%DB_NAME%" Driver="%DB_DRIVER%" Url="%DB_URL%" User="%USER%" Pass="%PASSWORD%" MaxConnections="10"/>
	</Databases>
	<Models>
		<Data_Model File_Name="security.xsd" File_Location="%XDAT_PROJECT%/schemas/security" DB="%DB_NAME%"/>
		<Data_Model File_Name="birnprov.xsd" File_Location="%XDAT_PROJECT%/schemas/birn" DB="%DB_NAME%"/>
		<Data_Model File_Name="xnat.xsd" File_Location="%XDAT_PROJECT%/schemas/xnat" DB="%DB_NAME%"/>
		<Data_Model File_Name="workflow.xsd" File_Location="%XDAT_PROJECT%/schemas/pipeline" DB="%DB_NAME%"/>
		<Data_Model File_Name="repository.xsd" File_Location="%XDAT_PROJECT%/schemas/pipeline" DB="%DB_NAME%"/>
		<Data_Model File_Name="project.xsd" File_Location="%XDAT_PROJECT%/schemas/project" DB="%DB_NAME%"/>
		<Data_Model File_Name="assessments.xsd" File_Location="%XDAT_PROJECT%/schemas/assessments" DB="%DB_NAME%"/>
		<Data_Model File_Name="catalog.xsd" File_Location="%XDAT_PROJECT%/schemas/catalog" DB="%DB_NAME%"/>
		<Data_Model File_Name="protocolValidation.xsd" File_Location="%XDAT_PROJECT%/schemas/validation" DB="%DB_NAME%"/>
		<Data_Model File_Name="screeningAssessment.xsd" File_Location="%XDAT_PROJECT%/schemas/screening" DB="%DB_NAME%"/>

		<Data_Model File_Name="ext.xsd" File_Location="%XDAT_PROJECT%/schemas/ext" DB="%DB_NAME%"/>
		<!-- Start modules schemas: Reserved for xnat_builder, don't modify anything between this line and the end modules line. -->
		<!-- End modules schemas: Reserved for xnat_builder, don't modify anything between this line and the start modules line. -->
	</Models>
</Instance_Settings>
